DEBUG: True
TESTING: True
ALLOWED_EXTENSIONS: ['mp4']
LOGFILE: app.log
UPLOAD_FOLDER: queue
RESULT_FOLDER: video_output
CELERY_BROKER_URL: redis://redis:6379/0
CELERY_RESULT_BACKEND: redis://redis:6379/0